// Step 0 (spec Section 8.4): list every real series in the Census New Home
// Sales program so the catalog can use confirmed codes.
//
//   npm run explore
//
// Writes docs/census-ressales-codes.md.

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fetchProgramFile, fetchProgramFromApi } from "@/lib/census/client";
import { parseCellValue, type EitsRow } from "@/lib/census/parse";
import { CATALOG } from "@/lib/datasets/catalog";
import { periodLabel } from "@/lib/period";

try {
  process.loadEnvFile();
} catch {
  // no .env file — fine
}

const FROM = "2020-01";

type Combo = {
  category: string;
  dataType: string;
  adj: string;
  geo: string;
  error: string;
  rows: EitsRow[];
};

function summarize(rows: EitsRow[]): Combo[] {
  const combos = new Map<string, Combo>();
  for (const row of rows) {
    if (row.time < FROM) continue;
    const key = [row.category_code, row.data_type_code, row.seasonally_adj, row.geo_level_code, row.error_data].join("|");
    let combo = combos.get(key);
    if (!combo) {
      combo = {
        category: row.category_code,
        dataType: row.data_type_code,
        adj: row.seasonally_adj,
        geo: row.geo_level_code,
        error: row.error_data,
        rows: [],
      };
      combos.set(key, combo);
    }
    combo.rows.push(row);
  }
  return [...combos.values()].sort((a, b) =>
    [a.error, a.category, a.dataType, a.geo, a.adj].join("|").localeCompare([b.error, b.category, b.dataType, b.geo, b.adj].join("|")),
  );
}

function recent(combo: Combo): string {
  return combo.rows
    .filter((r) => parseCellValue(r.cell_value) !== null)
    .sort((a, b) => a.time.localeCompare(b.time))
    .slice(-3)
    .map((r) => `${r.cell_value} (${periodLabel(r.time)})`)
    .join(", ");
}

async function main() {
  const lines: string[] = [];
  const out = (s = "") => {
    lines.push(s);
    console.log(s);
  };

  out("# Census New Home Sales (RESSALES) — confirmed codes");
  out();
  out(`Generated by \`npm run explore\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`);
  out();

  // --- 1. The EITS API -------------------------------------------------
  const apiKey = process.env.CENSUS_API_KEY;
  let apiRows: EitsRow[] | null = null;
  out("## Source 1: EITS API");
  out();
  out("`https://api.census.gov/data/timeseries/eits/ressales`");
  out();
  if (!apiKey) {
    out(
      "**Not checked — no `CENSUS_API_KEY` was set when this script ran.** The API now rejects requests without a key " +
        '(it answers with an HTML "Missing Key" page), so the API column names and the `time=from+YYYY` range syntax ' +
        "could not be verified here. Set a key in `.env` and run this script again to verify them.",
    );
  } else {
    try {
      apiRows = (await fetchProgramFromApi("ressales", apiKey, 2020)).rows;
      out(`Verified with a key: \`time=from+2020\` returned ${apiRows.length} rows.`);
      out();
      out(`Columns: ${Object.keys(apiRows[0] ?? {}).map((c) => `\`${c}\``).join(", ")}`);
    } catch (err) {
      out(`**The API call failed:** ${(err as Error).message}`);
    }
  }
  out();

  // --- 2. The downloadable data file -----------------------------------
  out("## Source 2: Download Data Sets file (fallback, no key needed)");
  out();
  out("`https://www.census.gov/econ_getzippedfile/?programCode=RESSALES` → `RESSALES-mf.csv`");
  out();
  const file = await fetchProgramFile("ressales");
  out(`Data updated on: ${file.updatedOnText ?? "unknown"}`);
  out();
  out("The file holds the same series as the API, from Jan 1963. The app converts it into the API's row shape");
  out("(`lib/census/parse.ts → parseDatasetFile`), so both sources go through the same parsing rules.");
  out();

  out("### Category codes");
  out();
  out("| Code | Meaning |");
  out("|---|---|");
  for (const [code, desc] of Object.entries(file.descriptions.categories)) out(`| \`${code}\` | ${desc} |`);
  out();
  out("### Data type codes");
  out();
  out("| Code | Meaning | Unit code |");
  out("|---|---|---|");
  for (const [code, d] of Object.entries(file.descriptions.dataTypes)) out(`| \`${code}\` | ${d.desc} | ${d.unit} |`);
  out();
  out("Unit codes: `K` = thousands of units (catalog `scale: 1000`), `DOL` = dollars, `MO` = number of months.");
  out();
  out("### Geo level codes");
  out();
  out("| Code | Meaning |");
  out("|---|---|");
  for (const [code, desc] of Object.entries(file.descriptions.geo)) out(`| \`${code}\` | ${desc} |`);
  out();

  // --- 3. Every distinct combination -----------------------------------
  const rows = apiRows ?? file.rows;
  out(`## Every distinct combination since ${periodLabel(FROM)} (${apiRows ? "from the API" : "from the data file"})`);
  out();
  out("| category_code | data_type_code | seasonally_adj | geo_level_code | error_data | rows | 3 most recent values |");
  out("|---|---|---|---|---|---|---|");
  for (const c of summarize(rows)) {
    out(`| ${c.category} | ${c.dataType} | ${c.adj} | ${c.geo} | ${c.error} | ${c.rows.length} | ${recent(c)} |`);
  }
  out();

  // --- 4. Catalog check ------------------------------------------------
  out("## Catalog check");
  out();
  out("| Catalog id | category | data type | adj | geo | Found? | First month | Latest month |");
  out("|---|---|---|---|---|---|---|---|");
  for (const def of CATALOG) {
    const s = def.source;
    const match = file.rows
      .filter(
        (r) =>
          r.error_data === "no" &&
          r.category_code === s.category_code &&
          r.data_type_code === s.data_type_code &&
          r.seasonally_adj === s.seasonally_adj &&
          r.geo_level_code === s.geo_level_code &&
          parseCellValue(r.cell_value) !== null,
      )
      .sort((a, b) => a.time.localeCompare(b.time));
    out(
      `| \`${def.id}\` | ${s.category_code} | ${s.data_type_code} | ${s.seasonally_adj} | ${s.geo_level_code} | ${
        match.length ? "yes" : "**NO**"
      } | ${match.length ? periodLabel(match[0].time) : "-"} | ${match.length ? periodLabel(match[match.length - 1].time) : "-"} |`,
    );
  }
  out();

  out("## Findings");
  out();
  out("- **Yearly pace** is its own category, `ASOLD` (\"Annual Rate for New Single-family Houses Sold\"), not `SOLD` with `seasonally_adj = yes`. `SOLD` only has not-adjusted monthly counts.");
  out("- **Average price** is data type `AVERAG` (six letters), not `AVERAGE`.");
  out("- **Northeast** is geo code `NO`, not `NE`. The others are `MW`, `SO`, `WE`, `US`.");
  out("- `TOTAL`, `NOTSTD`, `UNDERC`, `COMPED` values are in **thousands** of homes; prices are in dollars; `MONSUP` and `MMTHS` are in months.");
  out("- Rows with `error_data = yes` are relative standard errors (`E_TOTAL`, `E_MEDIAN`, …) and are skipped.");
  const quarterly = file.rows.some((r) => /Q/.test(r.time));
  out(
    `- **Official quarterly values:** ${
      quarterly ? "the file contains quarterly periods." : "none. Every time period in the file is a month, including for median and average price."
    } So quarterly prices are computed as the average of the 3 monthly values (catalog \`quarterlyFallback: "average"\`).`,
  );
  out("- The file lists months that have not been published yet (to the end of the current year) with no rows; they are ignored.");

  const dest = path.join(process.cwd(), "docs", "census-ressales-codes.md");
  mkdirSync(path.dirname(dest), { recursive: true });
  writeFileSync(dest, lines.join("\n") + "\n", "utf8");
  console.log(`\nSaved ${dest}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
